export const GET_ALL_CATEGORIES_LIST = "GET_ALL_CATEGORIES_LIST";
export const GET_ALL_CATEGORIES_LIST_SUCCESS =
  "GET_ALL_CATEGORIES_LIST_SUCCESS";
export const GET_ALL_CATEGORIES_LIST_FAILURE =
  "GET_ALL_CATEGORIES_LIST_FAILURE";

export const GET_CATEGORY_MENU_BY_CATEGORY_NAME =
  "GET_CATEGORY_MENU_BY_CATEGORY_NAME";
export const GET_CATEGORY_MENU_BY_CATEGORY_NAME_SUCCESS =
  "GET_CATEGORY_MENU_BY_CATEGORY_NAME_SUCCESS";
export const GET_CATEGORY_MENU_BY_CATEGORY_NAME_FAILURE =
  "GET_CATEGORY_MENU_BY_CATEGORY_NAME_FAILURE";

export const GET_ALL_FAVOURITES_LIST = "GET_ALL_FAVOURITES_LIST";
export const GET_ALL_FAVOURITES_LIST_SUCCESS =
  "GET_ALL_FAVOURITES_LIST_SUCCESS";
export const GET_ALL_FAVOURITES_LIST_FAILURE =
  "GET_ALL_FAVOURITES_LIST_FAILURE";

export const GET_RANDOM_MEAL = "GET_RANDOM_MEAL";
export const GET_RANDOM_MEAL_SUCCESS = "GET_RANDOM_MEAL_SUCCESS";
export const GET_RANDOM_MEAL_FAILURE = "GET_RANDOM_MEAL_FAILURE";

export const GET_ALL_FEEDBACK_LIST = "GET_ALL_FEEDBACK_LIST";
