export const GET_ALL_CATEGORIES_LIST = "GET_ALL_CATEGORIES_LIST";
export const GET_ALL_CATEGORIES_LIST_SUCCESS =
  "GET_ALL_CATEGORIES_LIST_SUCCESS";
export const GET_ALL_CATEGORIES_LIST_FAILURE =
  "GET_ALL_CATEGORIES_LIST_FAILURE";
